### ISSUE TITLE
Upgrade to Node.js 10

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-test#1079]
Upgrade to Node.js 10 as soon as fabric8-ui upgrades.

There is a new API in Node.js 10.12 - you can do mkdirSync recursively so we can remove dependency `mkdirp`

**Comment by ppitonak** [comment]
You just use it for development and build, don't you? Is it used in prod anywhere? I don't understand what role does Service Delivery plays here.

**Comment by joshuawilson** [comment]
Node is used to build prod.
