### ISSUE TITLE
Update PR checks for saas-openshiftio to cancel build on update

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-test#1083]
I had to revert  use of `cancel-builds-on-update` because 

1. duffy node would not be released
2. the tests would continue running and at some point would reset the account, new run would fail randomly

https://docs.openstack.org/infra/jenkins-job-builder/publishers.html?highlight=abort#publishers.postbuildscript could help

**Comment by ljelinkova** [comment]
It is not gonna happen because it would introduce a whole new pile of problems.
