### ISSUE TITLE
Unable to start ee_tests docker image on mac osx

### ISSUE THREAD

**Issue by christianvogt** [fabric8io/fabric8-test#1123]
Using `npm run image:build && npm run image:start` I get the following error:

```
The path /etc/localtime
is not shared from OS X and is not known to Docker
```

A quick search on google shows that mac users all over are affected by this issue.

There may be a way to fix it at the client where each mac user must apply the fix, but it would be nice if we could have a fix at the docker image instead.

**Comment by ppitonak** [comment]
We sync this file to the container so that there is the same timezone inside the container as on host system. 

@ljelinkova since it doesn't work reliably and fails on Mac, I suggest to remove it. WDYT?
