### ISSUE TITLE
Build logs are retrieved also for che project

### ISSUE THREAD

**Issue by ljelinkova** [fabric8io/fabric8-test#1159]
In oc-get-project-logs.sh, the logs for jenkins build are not withing the "run only in jenkins" block. As a result, the Jenkins logs are retrieved also when saving logs for che project.

**Comment by ppitonak** [comment]
I this code inside jenkins block:
```
if [[ -z "$POD_NAMES" ]]; then
    echo "No running jenkins pods"
  else
    echo "oc logs" $POD_NAMES
    oc logs $POD_NAMES
  fi
```

**Comment by ljelinkova** [comment]
Done.
