### ISSUE TITLE
Wait for the analytics report to be generated

### ISSUE THREAD

**Issue by ljelinkova** [fabric8io/fabric8-test#1171]
Investigate if we could wait for the report to be generated

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-released/3930/07-01-afterEach.png

**Comment by ppitonak** [comment]
According to https://github.com/openshiftio/openshift.io/issues/3744#issuecomment-436933246 the anlaytics report should be generated in no more than 30 minutes

**Comment by ljelinkova** [comment]
Yes, but what it means for the tests? We cannot wait 30 minutes. But maybe if we could wait at least 5 more minutes, we could make more tests pass.

**Comment by ljelinkova** [comment]
Done
