### ISSUE TITLE
Sleep necessary in importing an application flow

### ISSUE THREAD

**Issue by sanketpathak** [fabric8io/fabric8-test#1192]
I am running tests for import flow without using sleep and instead replacing it with the wait but it is failing with timeout and not passing. Continue button is not working as seen in the picture provided. Browser.sleep seems to be promisable solution for now.

![01-01-aftereach](https://user-images.githubusercontent.com/10252230/49440761-845e9880-f7ea-11e8-9077-de26410981c0.png)

**Comment by ppitonak** [comment]
See [this code](https://github.com/fabric8io/fabric8-test/blob/master/ee_tests/src/interactions/account_home_interactions.ts#L63) for how we handle creating a space. Do something similar for import.

**Comment by sanketpathak** [comment]
I have handled it according to the create codebase method like [this](https://github.com/fabric8io/fabric8-test/blob/587607edd96b9a746f4b16a1cb432109dcb319d8/ee_tests/src/page_objects/launcher.page.ts#L22).
