### ISSUE TITLE
Failue while pulling docker image

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-test#12]
Step 17 : COPY ../analytics_EE_tests/ $WORKSPACE
Forbidden path outside the build context: ../analytics_EE_tests/ ()
Unable to find image 'fabric8-ui-builder:latest' locally
Pulling repository docker.io/library/fabric8-ui-builder
docker: Error: image library/fabric8-ui-builder:latest not found.
See 'docker run --help'.
Error response from daemon: No such container: fabric8-ui-builder
Error response from daemon: No such container: fabric8-ui-builder
Error response from daemon: No such container: fabric8-ui-builder
Error response from daemon: No such container: fabric8-ui-builder

**Comment by naina-verma** [comment]
Fix of this https://github.com/fabric8io/fabric8-test/pull/13

**Comment by nainav** [comment]
fixed !
