### ISSUE TITLE
lets remove the use of local_cleanup.sh / local_cleanup_che.sh and instead use the new `Reset Environment` 

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-test#128]
Lets use the `Update Profile` page of the `Profile` page (either navigating via the top right drop down or using the canonical URL of `$URL/_profile/_update` when the new canonical https://openshift.io/_profile page goes live in prod today hopefully) - and then click the `Reset Environment` button before the test to ensure things are all cleaned down etc

**Comment by ldimaggi** [comment]
The use of the cleanup scripts is a short-term workaround. The tests had been failing due the reset operation requiring up to 20 min to restart Che - see: https://github.com/openshiftio/openshift.io/issues/666

The PR adds options to selectively restart Che and/or Jenkins:
https://console.starter-us-east-2.openshift.com/console/project/ldimaggi-osiotest1-jenkins/overview

**Comment by ldimaggi** [comment]
Will leave this issue open until this issue - https://github.com/openshiftio/openshift.io/issues/666 - is resolved to the extent that the tests can depend on Che and Jenkins restarting in a timely manner.

**Comment by jstrachan** [comment]
cool - as a workaround for now I've added a boolean around it so we can ignore those scripts when testing fabric8 https://github.com/fabric8io/fabric8-test/pull/131

**Comment by ppitonak** [comment]
Closing in favor of https://github.com/fabric8io/fabric8-test/issues/500
