### ISSUE TITLE
parameterise the E2E tests so we can specify tenant parameters

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-test#129]
if you navigate to the new tenant page there are a number of properties you can customise on a per tenant basis now: https://openshift.io/_profile/_tenant

so these can be used to test a specific PR of the jenkins / che / team YAML using a custom maven repository etc. Or they can be used to test a specific PR / fork of the Forge booster catalogs.

So it'd be nice to be able to pass in all those values (optionally) to the E2E test and if any of the values are present, to navigate to the page: https://openshift.io/_profile/_tenant then update the form and click the `Save and Update Tenant` button before running the tests - then clearing the values at the end of the test.

This will mean we can reuse the E2E tests and pass in environment variables for these values to test PRs of booster catalogs or che/jenkins/team YAMLs

**Comment by ldimaggi** [comment]
Closing as obsolete.
