### ISSUE TITLE
if a test fails can we (optionally) keep the browser window open?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-test#140]
when tests fail due to some missing UI button/feature not being found; it'd be nice to keep the browser window open for a while so we can try grok why the test failed; sometimes the message isn't super clear so it'd be nice to fix up the test to make things more obvious what went wrong & why. Sometimes its just the test needs to be a bit more clever/resilient - sometimes its a real bug/issue but just not reporting the real error nicely.

So it'd be nice to have a flag we can use to keep the browser around, giving the user a chance to look at where the browser got to & maybe grabbing the HTML and whatnot to try figure out what went wrong if the failure message is not good/obvious

I've tried googling and adding optional shutdown hooks to the protractor config.js to no avail so far - anyone else figured out a nice way?

**Comment by ldimaggi** [comment]
The best approach that I have found so far with this is to assign a long duration timeout when looking for UI elements. If you are watching the test run, you can interact withthe UI during these long timeout periods. Not ideal, I know, but the best that I have found so far...

**Comment by jstrachan** [comment]
yeah - when you don't know where the UI is gonna fail and it takes 5 mins to run the test; you then have to let it fail, find a good spot to add a wait then restart - which is kinda sucky - we just want to delay closing the webdriver chrome window really on any failure. Also that assumes the test behaves identically in both runs - which isn't always the case ;)

**Comment by jstrachan** [comment]
there must be some way to add a generic wait before the selenium webdriver connection/driver is closed - just not sure how yet ;)

**Comment by jstrachan** [comment]
tried adding `onComplete` or `onCleanUp` to the config.js but didn't seem to be invokved

**Comment by jstrachan** [comment]
another approach could be - can we dump the HTML source and an image of the last page before we close down selenium? Then at least we could open it and look for the state of the DOM and see what UI widgets/IDs/CSS/XPath stuff was left

**Comment by ldimaggi** [comment]
Closing - the tests now archive screenshots and html pages.
