### ISSUE TITLE
when working on tests, it'd be nice to reuse the browser session & reuse the login?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-test#141]
it can take a while to login from scratch each time; then clean down tenants etc. It might be nice to add some optional short circuit flags via env vars to let tests run faster by reusing a browser session & minimising re-logging in each time we create a quickstart or whatever

e.g. if you just want to re-run the create quickstart test which maybe has some issue multiple times locally; it'd be nice to not have to totally login from scratch, delete + recreate your tenant etc

**Comment by ldimaggi** [comment]
Closing as obsolete.
