### ISSUE TITLE
use typescript for test code?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-test#143]
I'm used to writing TypeScript for UI stuff rather than pure JavaScript and I'm surprised how many compile errors get missed when working on test code ;) Plus we lose lots of nice IDE completion due to lack of known types etc

I wonder if we could switch to TypeScript for the test code but still keep the rapid develop / debug cycle of working on the E2E Tests?

**Comment by joshuawilson** [comment]
I agree, we should be using TS where ever possible. If it is a compile issue, let me know. We can transpile before running the tests.

**Comment by jstrachan** [comment]
yeah - usually we run protractor directly without a build step (e.g. from an IDE or CLI: https://github.com/fabric8io/fabric8-test/tree/master/ee_tests#running-the-e2e-tests-in-intellij-idea) which is super handy - I wonder if we could get protractor to handle the transpiling on the fly (like how when you add typescript as a script language to a browser)

**Comment by ldimaggi** [comment]
YES - this migration to typescript is in progress now.

**Comment by ldimaggi** [comment]
See: https://openshift.io/openshiftio/openshiftio/plan/detail/1620

**Comment by ppitonak** [comment]
All new code is in TS, closing.
