### ISSUE TITLE
Refactor tests to replace object references that rely on xpath text to use UI element ID's

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-test#150]
The tests today are too brittle - references to objects' xpaths should be replaced with object ID's.

**Comment by rgarg1** [comment]
That's a good task to be taken up! However, we must remember that all xpath references may not be eliminated as certain dynamic UI elements need xpaths.

**Comment by ldimaggi** [comment]
This is an ongoing task - and will continue to be performed as the product code is developed.
