### ISSUE TITLE
on test failure lets run a number of oc commands and capture their output so we can more easily diagnose why things go wrong

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-test#187]
e.g. 
```
oc export bc -n ${ID}
oc get dc -n ${ID}-stage
oc get pod -n ${ID}-stage
oc get dc -n ${ID}-run
oc get pod -n ${ID}-run
```
we can tweak them over time. It'd be nice to know what the current space name is when the test failed too.

Note the above are useful for quickstart/import failures; they're less useful for diagnosing che failures

**Comment by ldimaggi** [comment]
https://github.com/fabric8io/fabric8-test/pull/225
