### ISSUE TITLE
cheTest fails to list projects (may be related to @ char in username)

### ISSUE THREAD

**Issue by l0rd** [fabric8io/fabric8-test#197]
@ibuziuk could not run cheTest because it fail to list projects in osio. The only difference we could spot between my accound and his is that @ibuziuk osio's login is his email: ibuziuk@redhat.com. He can't login using username ibuziuk, he needs to provide his full email.

**Comment by l0rd** [comment]
Here are the instructions we use to run Che e2e tests:

```bash
# Clone fabric8-test
git clone git@github.com:fabric8io/fabric8-test.git

# Install npm packages
cd ee_tests
npm install
npm install -g webdriver-manager
webdriver-manager update
webdriver-manager update --versions.chrome 2.29

# Trick that make as if oc is in current folder
ln $(which oc) $(pwd)/oc

# Run tests
export OSIO_URL=https://openshift.io
export TEST_SUITE=cheTest
export RHD_USERNAME=<RedHatDeveloper Username>
export RHD_PASSWORD=<RedHatDeveloper Password>
export OSO_TOKEN=<OSO OpenShift Token>
export KC_TOKEN=<KC Token>
export GH_USERNAME=<GitHub user linked with RHD account>
sh ./local_run_EE_tests.sh ${RHD_USERNAME} \
                           ${RHD_PASSWORD} \
                           ${OSIO_URL} \
                           ${OSO_TOKEN} \
                           ${KC_TOKEN} \
                           ${TEST_SUITE} \
                           ${GH_USERNAME}
```

**Comment by ibuziuk** [comment]
thanks @l0rd for creating this issue. Yeah, I wanted to verify `https://github.com/redhat-developer/rh-che/issues/283` via e2e tests but it fails to log developers.redhat.com with `RHD_USERNAME` (ibuziuk), if I put valid login (ibuziuk@redhat.com) tests fails when trying to list the projects on prod cluster. It looks like there should be separate env vars for oso & `developers.redhat.com` logins

![image](https://user-images.githubusercontent.com/1461122/30798949-89ccfe3a-a1db-11e7-90c2-aca35e951330.png)

**Comment by ldimaggi** [comment]
Please try again - this PR should have the problem resolved for you:
https://github.com/fabric8io/fabric8-test/pull/198
