### ISSUE TITLE
Testcase Test-1704E469-02 should match for exactly the same set

### ISSUE THREAD

**Issue by luebken** [fabric8io/fabric8-test#22]
The expected result for Licenses on `io.vertx:vertx-core/3.4.1` is two licenses: Apache and MIT. See also https://mvnrepository.com/artifact/io.vertx/vertx-core/3.4.1

The API returns three licenses:
```
curl -sH "Authorization: Bearer $OSIO_TOKEN" https://recommender.api.openshift.io/api/v1/component-analyses/maven/io.vertx:vertx-core/3.4.1 | jq .result.data[0].version.licenses
[
  "Apache 2.0",
  "EPL 1.0",
  "MIT License"
]
```
But the testcase only checks if the results of the API is in the set of Apache and EPL. The additional MIT License should make the test fail.

**Comment by ljelinkova** [comment]
Outdated.
