### ISSUE TITLE
Refactor EE import tests to accept project repo as parameter - for booster tests

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-test#223]
So that the tests can can run against any repo - including all boosters.

**Comment by ldimaggi** [comment]
See PR:  https://github.com/fabric8io/fabric8-test/pull/226

**Comment by ppitonak** [comment]
Is this issue still valid? There was some related work done by @pmacik recently

**Comment by ldimaggi** [comment]
Yes - this is related to:  https://openshift.io/openshiftio/openshiftio/plan/detail/2407

We should close this issue and track the work here: https://openshift.io/openshiftio/openshiftio/plan/detail/2407
