### ISSUE TITLE
allow 'just jenkins' or 'just che' flavours of the E2E tests

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-test#262]
it would be nice to be able to just run Jenkins tests and ignore Che and vice versa so that we can run the E2E tests in the che & jenkins pipelines and avoid unnecessary time and resources spent testing if Che works or Jenkins

I figure we could just introduce some environment variable that gets populated into  the browser params:
https://github.com/fabric8io/fabric8-test/blob/master/ee_tests/protractorEE-env.config.js#L88-L120

that makes the tests ignore the Jenkins parts or the Che parts

**Comment by ldimaggi** [comment]
See: https://github.com/fabric8io/fabric8-test/pull/264

Is this what you had in mind?

**Comment by jstrachan** [comment]
its a good start;  even when running a quickstart test for Jenkins it looks like the code still waits for Che to be there etc. I'd forgotten I'd added the `browser.params.target.disableChe` flag mind you to disable that - so we might be good enough - lets see how it works out...

**Comment by ppitonak** [comment]
Not compatible with #494
