### ISSUE TITLE
provide an option to reuse the UIs 'Reset Environment' 

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-test#263]
we really should be using a fully clean and up to date tenant when running the full E2E tests - so using the UI's Profile -> Reset Environment UI to ensure that the tenant is totally cleaned before the test and that the most up to date tenant software is used (plus taking into account any PR for jenkins / che / boosters being tested too)

So it'd be nice to do something like:

* reset the enivronment using the UI (so it really does a full reset & update of tenant before tests)
* run just the Jenkins / pipeline tests first (which seem to work fine after a full reset)
* only when all that has happened, try testing Che (which by then should have started ;)

**Comment by ldimaggi** [comment]
YES! That is now and has always been our intention. The various "clean" scripts are a stop gap measure as the 'reset env' feature sometimes fails - see: https://github.com/openshiftio/openshift.io/issues/1034 - - and can take too long to run.

When the 'reset env' feature is more reliable, we will update the tests to use that and remove the "clean" scripts. Thx!

**Comment by ldimaggi** [comment]
For example:  https://github.com/openshiftio/openshift.io/issues/1034#issuecomment-336489961

**Comment by ldimaggi** [comment]
Closing - the tests reset the user env.
