### ISSUE TITLE
Explore use of BDD tools to generate feature coverage

### ISSUE THREAD

**Issue by sthaha** [fabric8io/fabric8-test#273]
The proposal is to explore tools (like cucumber) where we can define Features and test scenarios which would provide us some insight into what Features and scenarios are being tested.

**Comment by joshuawilson** [comment]
We do have a PR that was never finished on BDD. https://github.com/fabric8-services/fabric8-wit/pull/678 

Maybe you can use some of what is in there, maybe not. But worth a look.

**Comment by sthaha** [comment]
@joshuawilson I like the idea of using gherkin for BDD but since the UI tests use Javascript/typescripts I would try something like - https://github.com/cucumber/cucumber-js

**Comment by ppitonak** [comment]
@sthaha what component is this issue for?

**Comment by ldimaggi** [comment]
We should revisit/re-open this idea - new BDD tests can be used to augment the existing E2E tests. Ideally, the the BDD tests can be implemented in a form (coding through the API and not the UI)  that will make them easier to maintain.

**Comment by ljelinkova** [comment]
Outdated.
