### ISSUE TITLE
Use container image to simplify creation of development and test env

### ISSUE THREAD

**Issue by sthaha** [fabric8io/fabric8-test#279]
Currently we have development and test env that is setup differently. Development env itself can be different based on how it is create -  using `nvm` or `system-packages` and running the test can break due to these differences.

As a solution to this lets use a Docker image that provides the necessary tools `node`, `npm`, `yarn` and use that to run tests locally and in CI. The goal is to make it easy to reproduce failures.

**Comment by ppitonak** [comment]
@sthaha what component is this issue for?

**Comment by ljelinkova** [comment]
Outdated.
