### ISSUE TITLE
Run E2E tests in headless mode instead of using xvfb

### ISSUE THREAD

**Issue by sthaha** [fabric8io/fabric8-test#289]
It seems the tests are run using xvfb instead of running chrome in [headless mode](https://developers.google.com/web/updates/2017/04/headless-chrome) `--headless` `--disable-gpu` 

Please note that I did not find any _significant_ difference in the run time of tests under normal and headless mode.

**Comment by rgarg1** [comment]
So the chrome headless mode run is successful! Sounds great. The last time we tried, we ran into failures.

**Comment by sthaha** [comment]
@rgarg1 I am interested to know what those failures were. Have created an issue to track these?

**Comment by rgarg1** [comment]
@sthaha Can you submit a PR to enable headless chrome testing?

**Comment by ppitonak** [comment]
Can we close this issue?

**Comment by sthaha** [comment]
This may be more relevant now with ["End of Phantom.js development"](https://github.com/ariya/phantomjs/issues/15344) since the unit and the functional may now need to run on chrome headless

**Comment by ppitonak** [comment]
Tests inside `ee_tests` directory don't use Phantom.js but Chrome... it this issue about these tests or something different?
