### ISSUE TITLE
Refactor space_dashboard.page.ts file

### ISSUE THREAD

**Issue by jarifibrahim** [fabric8io/fabric8-test#336]
The [space_dashboard.page.ts](https://github.com/fabric8io/fabric8-test/blob/master/ee_tests/src/specs/page_objects/space_dashboard.page.ts) file contains page objects for `planner` also. This should be moved to a separate `Planner` directory.

Also, there are few `ui` elements like
1. [newSpaceName = $('#name')](https://github.com/fabric8io/fabric8-test/blob/master/ee_tests/src/specs/page_objects/space_dashboard.page.ts#L153)
2. [createSpaceButton = $('#createSpaceButton')](https://github.com/fabric8io/fabric8-test/blob/master/ee_tests/src/specs/page_objects/space_dashboard.page.ts#L154)
3. [devProcessPulldown = $('#developmentProcess')](https://github.com/fabric8io/fabric8-test/blob/master/ee_tests/src/specs/page_objects/space_dashboard.page.ts#L155)
that no longer exists on the `openshift.io/<user>/<spacename>` page. These too should be removed.

**Comment by ljelinkova** [comment]
Outdated.
