### ISSUE TITLE
Tests are failing due to hardcoded github name

### ISSUE THREAD

**Issue by vpavlin** [fabric8io/fabric8-test#353]
See https://ci.centos.org/view/Devtools/job/devtools-test-end-to-end-idling-prod-preview.openshift.io-quickstartTest/67/console

Claims to fail at: https://github.com/fabric8io/fabric8-test/blob/master/ee_tests/src/tests/work-item/work-item-list/EE/openshift-io-burr-quickstart.spec.js#L182

Expects:  https://github.com/osiotestmachine/testdec111512979686955.git
Value to expect: https://github.com/vpavlin/testdec111512979686955.git

**Comment by ldimaggi** [comment]
This change - to remove the hard-coded git username is pending this open issue/request:  https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/846

**Comment by ppitonak** [comment]
Is this issue still valid?

**Comment by ldimaggi** [comment]
The name is now configured as a variable in the cico jobs yaml file. Closing.
