### ISSUE TITLE
Remove ts-protractor.sh

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-test#471]
`ts-protractor.sh` script does two things - forwards env variables to Protractor and decides if Proctractor should run in debug mode, both of these could be done directly so IMHO `ts-protractor.sh` is not needed.

See https://github.com/rhoar-ci/e2e-tests/blob/master/conf.ts#L39 for alternative way of setting Protractor.

**Comment by ljelinkova** [comment]
We decided to keep the file for now.
