### ISSUE TITLE
Refactor support.writeScreenshot

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-test#472]
Method `support.writeScreenshot` usually takes path to the file like `target/screenshots/something.png`. `target/screenshots` can be either configurable or hard-coded but definitely should not be in every test.

Test would contain `support.writeScreenshot('x.png')` and it would be saved e.g. to 'target/screenshots/x.png'.

Related to this, create naming conventions for screenshots so that it's clear which file to look at when investigating Jenkins job/local run failures. (feel free to separate to a new issue).

**Comment by ljelinkova** [comment]
https://github.com/fabric8io/fabric8-test/pull/786

**Comment by ljelinkova** [comment]
Done.
