### ISSUE TITLE
Review usage of dist dir in cico_run_EE_tests_ts.sh

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-test#473]
Script `cico_run_EE_tests_ts.sh` creates a directory name `dist` and attaches it as a volume to docker container but it seems that it's not being used.

1. Could we use it instead of `target` for storing test run artifacts?
2. Could we rsync test artifacts from Jenkins slave directly, not from Duffy node which would shorten this script and made it more readable.

**Comment by ljelinkova** [comment]
Addressed in https://github.com/fabric8io/fabric8-test/pull/1267

**Comment by ljelinkova** [comment]
Done in https://github.com/fabric8io/fabric8-test/pull/1267
