### ISSUE TITLE
Review return code handling in cico_run_EE_tests_ts.sh

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-test#474]
There is `grep TimeoutError` and `grep 0 faillures` in `cico_run_EE_tests_ts.sh` which should not be there.

In the past, it was usual for tests to fail with a timeout and Protractor/Jasmine reported it as a pass which led to this workaround in cico_run_EE_tests_ts.sh. Tests were fixed so this should not be necessary anymore.

Slightly related to issue #473 (implementation of this issue would make implementation of this issue easier).

EDIT 20180409: smoke tests should report more data to Zabbix (#494), it's releated to this issue

**Comment by ldimaggi** [comment]
The TimeoutError does not refer to an error in OSIO not displaying a UI element. It was added to the test to workaround errors in Protractor where we were seeing unstable behavior by Protractor. Tests would run successfully, but then report a random TimeoutError.

**Comment by ppitonak** [comment]
I believe that these errors were not random but caused by incorrect error handling in test code which should be fixed now.

**Comment by ppitonak** [comment]
related to #494

**Comment by ljelinkova** [comment]
Done in https://github.com/fabric8io/fabric8-test/pull/1268
