### ISSUE TITLE
Review the way we reset environment

### ISSUE THREAD

**Issue by ljelinkova** [fabric8io/fabric8-test#493]
Test ee_tests/src/specs/quickstart_cheterminal.spec.ts  resets its environment  in the beforeEach() method. It think that the test should not do that directly, it should assume that it can run safely on any environment that is prepared for it. 

This is the explanation why are things done this way:
https://github.com/fabric8io/fabric8-test/pull/463#discussion_r171603752

But I think that there is another possibility - to create 4th Jenkins job that would ran after the 3 jobs are finished. The sole purpose of this job would be to reset the environment. As a result, the tests would be completely clean of "reset environment" tasks.

**Comment by ldimaggi** [comment]
I like the idea of removing the reset from the actual test, and placing it in a separate test.  Be aware, however, the env reset is not 100% reliable. See these open issues: https://github.com/openshiftio/openshift.io/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+author%3Aldimaggi+reset

Notwithstanding these open issues, I still agree that moving the reset to a separate test is a good idea. If you implement this change, be sure to coordinate the change with the addition of the 4th test in the cico jobs repo.

**Comment by ppitonak** [comment]
Related to #500

**Comment by ljelinkova** [comment]
This issue is no longer relevant.
