### ISSUE TITLE
Remove old bash scripts and config files

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-test#497]
* [ ] remove script run_EE_tests.sh
* [ ] remove script cico_run_EE_tests.sh
* [ ] remove protractorEE.config.js
* [x] remove template `devtools-test-end-to-end-{test_url}-{test_suite}` and all jobs using it from [cico yaml](https://github.com/openshiftio/openshiftio-cico-jobs/blob/master/devtools-ci-index.yaml) (all of them are disabled)

**Comment by ppitonak** [comment]
@ldimaggi is it safe to remove disabled e2e jobs from CICO yaml?

**Comment by ldimaggi** [comment]
They have been disabled for some time and no one has raised a concern. I think the time is now to remove them. One thing to look for - verify that no other tests are relying on any of the legacy EE tests' templates before you remove them. Thx!

**Comment by ppitonak** [comment]
I already checked that and it seems to be ok.

**Comment by ljelinkova** [comment]
Fixed by https://github.com/fabric8io/fabric8-test/pull/561
