### ISSUE TITLE
Update cleanup scripts

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-test#500]
There are multiple scripts in ee_tests that are supposed to do cleanup:

* `local_cleanup*.sh`
* `local_osio_cleanup`
* `clean_test_repos.sh`
* multiple helper scripts? `local_oc_data.sh`, `local_oc.sh`

1. Find out if they are still useful/used.
2. (a very old version of) `oc` binary is being downloaded in Dockerfile.builder and it's being used only by these scripts - either update it to latest version or remove it
3. If `oc` is still necessary, could it be downloaded from [official mirror](https://mirror.openshift.com/pub/openshift-v3/clients/) instead of GitHub?

**Comment by ldimaggi** [comment]
Some history is needed to explain these scripts.

Our goal has always been to provide each test with a clean starting environment. This is always a good idea for tests and is even more important for OSIO tests as the user accounts in which we run our tests are provisioned in the OSO free tier, and therefore have limited resources configured.

These scripts were originally written to provide a reliable means to "clean" a user environment by deleting build configs and deployment configs in OSO through the oc client. The scripts were never fully successful as the product was changing quickly and the scripts did not restart the Jenkins and Che pods. 

The tests stopped using these scripts when the "env reset" feature was added to OSIO.

The env reset feature, however, is not 100% reliable and can leave OSO in a state where it can require several minutes for the Jenkins pod to full restart. See issue: https://github.com/openshiftio/openshift.io/issues/1790

The best long term solution is a "user cleanup" feature that will remove a user's applications, and free up the user's OSO resources, without leaving the Jenkins pod in an unusable state. This feature has been talked about but is not part of the Summit plan.

**Comment by ppitonak** [comment]
To sum it up,

1. cleanup scripts are not usable at the moment
2. we should focus on proper "user cleanup", not on cleanup scripts

Do I get it right? If yes, we should delete these scripts.

**Comment by ljelinkova** [comment]
Outdated.
