### ISSUE TITLE
Post-mortem on March 7, 2018 E2E test failures

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-test#508]
At about 04:00 UTC on March 7, 2018 - all E2E started failing. The issue was traced to a version mistake for Chromedriver and was repaired in this pull request:  https://github.com/fabric8io/fabric8-test/pull/507

Topics and actions to take:

- [ ] The failures were noticed during a manual inspection of the tests running on Centos CI. In future, we will want Zabbix to automatically track state changes in test results and notify Lucia, Pavol, Len in email. See: https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1460

- [x] json.package included a hard-coded reference to chromedriver version 2.33 - this was resolved in pull request https://github.com/fabric8io/fabric8-test/pull/507

- [ ] Multiple scripts also include hard-coded references to chromedriver version 2.33 - most of these are outdated and will be removed soon.

- [ ] Ongoing monitoring of webdriver/chromedriver errors is required. The reason that version 2.33 of chromedriver was hard-coded was in response to errors specific to version 2.35. In the past, similar hard-coding of version 2.29 was needed as version 2.31 failed. 

- [ ] Additional error handling is needed for login failures to assist us in debugging login problems. See: https://github.com/fabric8io/fabric8-test/issues/506

**Comment by kpiwko** [comment]
Hello guys,

I wanted to comment on this one - the same thing I said to Len:

I believe that unlocking chromedriver here is not the right thing. We can't guarantee that Chrome + Chromedriver version would work and hence E2E tests might fail.

I would rather propose locking down Chrome version and Chromedriver version and establish a process that regularly updates both - so any regressions here do not impact test execution. To lock Chrome version, the easiest approach is to use selenium chrome docker images - https://github.com/SeleniumHQ/docker-selenium

Karel

**Comment by ppitonak** [comment]
I agree with Karel that it should be locked. Using the latest version was just s quick fix.

Long term solution should be to define version of Chrome driver in package.json. We want to first remove all legacy scripts that also define driver version.

I've never used Selenium Chrome docker images but we don't want neither multi-container setup nor using it as a base image at this point.

**Comment by lordofthejars** [comment]
We have support in Arquillian for that. You can check Arquillian Cube
project for examples.

**Comment by ppitonak** [comment]
Closing this issue, next step is #468
