### ISSUE TITLE
EE test suggested by KB - Returning-developer

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-test#518]
EE test suggested by KB - Returning-developer:
* In Che editor, edit index.html to alter project
* In Che terminal window, execute: mvn clean compile test
* In Che, execute Junit test
* In Che, run the application
* In Che terminal window, execute: curl localhost:8080/api/greeting?name=test
* In Che, commit changes to git
* In Che, execute git push
* In github, verify code changes were saved
* In OSIO, verify that github webhook fired and project pipeline is running

**Comment by ljelinkova** [comment]
Outdated.
