### ISSUE TITLE
Review the existing specs

### ISSUE THREAD

**Issue by ljelinkova** [fabric8io/fabric8-test#524]
I've been looking into what specs do we have and I've noticed several specs that are not in the configuration file (protractorTS.config.ts)
What shall we do with these files? Could they be removed?
```
booster_ee_int_tests
landing_page.spec.ts
newspace.spec.ts
planner-simple-create.spec.ts
workshop-quickstart.spec.ts
workshop-setup.spec.ts
```
Some files are in the configuration file but seem legacy to me - could they be removed?
```
workshop-import-to-space.spec.ts
booster_pipeline.spec.ts
```

**Comment by ljelinkova** [comment]
@ldimaggi do you have any insights about the never used specs?

**Comment by ldimaggi** [comment]
```
booster_ee_int_tests - I cannot find this file/dir
landing_page.spec.ts - legacy, this can be removed
newspace.spec.ts -  legacy, this can be removed
planner-simple-create.spec.ts - I would retain this file as we do not yet have planner tests
workshop-quickstart.spec.ts - legacy, this can be removed
workshop-setup.spec.ts - legacy, this can be removed
```

**Comment by ldimaggi** [comment]
I would prefer us to retain these as working examples - at least until we have tests in place to perform the same tasks:

```
workshop-import-to-space.spec.ts
booster_pipeline.spec.ts
```

Thx!

**Comment by ppitonak** [comment]
Outdated
