### ISSUE TITLE
Run deployment tests on Jenkins

### ISSUE THREAD

**Issue by ljelinkova** [fabric8io/fabric8-test#539]
I'd like to replace quickstart_pipeline.spec.ts by quickstart_deployments.spec.ts. The latter one contains the same tests as the former one but in addition it contains also deployment tests. 

This would be our first step toward creating one robust test case across all OSIO functions. 

@ldimaggi  Do you agree?

**Comment by ppitonak** [comment]
Related to #494

**Comment by ldimaggi** [comment]
That sounds good to me! 

One thing to confirm before you perform the replacement - the smoke test running on Centos CI relies on this test - can you check and confirm that there will be zero effect on the tests running on Centos CI? Thx!

**Comment by ppitonak** [comment]
I verified yesterday that the test logic is correct but we can never be 100% sure that it's ok

**Comment by ldimaggi** [comment]
If the test runs cleanly (locally) with the "smoketest" suite name, then everything should be OK - thx!

**Comment by ljelinkova** [comment]
Fixed by #541.
