### ISSUE TITLE
Verify that no errors are present on page after every action

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-test#546]
Sometimes an error appear during the test... we should either log that fact or fail test (there is a risk that it's completely unrelated to test).

![pipeline_final_testmar211521630086100](https://user-images.githubusercontent.com/445100/37711016-ba73aa9c-2d0f-11e8-8b10-f65492a17c2e.png)

**Comment by ldimaggi** [comment]
Might it be sufficient to verify that zero elements of type error are present?
