### ISSUE TITLE
Remove references to obsolete credentials from cico-jobs definitions for E2E tests

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-test#549]
At one point in time, the E2E tests made use of shell scripts to "clean" the test account user environment by deleting OSO resources. These scripts are no longer in use.

The scripts relied on these credentials to access OSO:  oso_token_creds, kc_refresh_token_creds

These^ credentials should be removed from the cico-jobs definitions for the E2E tests.

**Comment by ppitonak** [comment]
addressed in https://github.com/openshiftio/openshiftio-cico-jobs/pull/667

**Comment by ppitonak** [comment]
The credentials were removed by PR mentioned in previous comment. Do we want to remove also some scripts in our repository?

**Comment by ldimaggi** [comment]
Those scripts were written in 2017 as temporary workarounds to failures with the env reset feature. We should remove these scripts as they are (1) not in use and (2) have not been maintained. Let's try to only have "live" code in the test repo. Thx!

**Comment by ppitonak** [comment]
Thanks for your reply, please see #743
