### ISSUE TITLE
Run E2E tests on prod-preview in an a test user account not provisioned on free-stg

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-test#553]
User accounts on prod-preview can be provisioned on either free-stg or a production cluster. At least some users are seeing problems unique to accounts on prod-preview that are not provisioned on free-stg (https://github.com/openshiftio/openshift.io/issues/2672).

Our E2E tests currently run only on a user account provisioned on free-stg - we should also run these tests on prod-preview with an account provisioned on a production cluster.

**Comment by ljelinkova** [comment]
Done.
