### ISSUE TITLE
Merge che tests into smokesuite

### ISSUE THREAD

**Issue by ljelinkova** [fabric8io/fabric8-test#572]
- merge che tests into the main smoketest suite
- delete jobs on Jenkins
- make sure the reset of environment works ok

**Comment by ldimaggi** [comment]
One thing to keep in mind is that we do not want increase the run/execution time for the current E2E tests as the tests are already time-consuming.

**Comment by ppitonak** [comment]
@ldimaggi actually, increased execution time of a smoke test is a side effect of #494 ... it will run more often and won't test the same things (login, create space, create project, pipeline) over and over so it's acceptable.

**Comment by ppitonak** [comment]
@ljelinkova can you provide more information for next step "delete jobs on Jenkins"?

**Comment by ljelinkova** [comment]
@ldimaggi Actually, the tests should not run much longer as the original smoketest because the che is tested after the quickstart is created and before we wait for pipeline to finish (so it runs during the build). The tests of dashboard are quite fast.

**Comment by ljelinkova** [comment]
@ppitonak Yes, it is chetest suite.

**Comment by ppitonak** [comment]
Closing, the rest of the issue will be handled in #579
