### ISSUE TITLE
Merge dashboard tests into smoketest

### ISSUE THREAD

**Issue by ljelinkova** [fabric8io/fabric8-test#573]
-    merge space dashboard tests into the main smoketest suite
 -   delete jobs on Jenkins
  -  make sure the reset of environment works ok

**Comment by ldimaggi** [comment]
One thing to keep in mind is that we do not want increase the run/execution time for the current E2E tests as the tests are already time-consuming.

**Comment by ppitonak** [comment]
@ljelinkova which test file/test suite represents "dashboard tests"?

**Comment by ljelinkova** [comment]
@ppitonak they are named "analytics" tests but they are actually testing the whole dashboard. So the suite names are analyticstest and quickstartTest. Sorry for the confusion.

**Comment by ppitonak** [comment]
Closing, the rest of the issue will be handled in #579
