### ISSUE TITLE
Refactor or remove e2e tests importing a project

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-test#578]
These two test suites seem to do the same thing and majority of it is already covered by smoke test. The only difference is that they import a project instead of creating new one from a booster.

* boosterTest: ['src/booster_pipeline.spec.js'],
* importTest: ['src/workshop-import-to-space.spec.js'],

Decide whether to refactor them or delete them.

**Comment by ljelinkova** [comment]
New import tests have been created.
