### ISSUE TITLE
How to test new features in OSIO

### ISSUE THREAD

**Issue by ljelinkova** [fabric8io/fabric8-test#586]
With new features coming into OSIO we are facing an issue of how to test them. The features are introduced gradually so we need to test application with and also without the features at the same time to make sure it works for different users. 

At the moment, there are 4 feature levels that can be set on the user profile - production, beta, experimental and internal. If we assumed that the feature would go from “internal” state through “experimental”, “beta” to  “production” we would need 4 user accounts to test the “production”, “beta”, “experimental” and “internal” application as a whole.

There are some questions that should be answered:
- can we assume that features will be introduced as described (moving from internal to production)?
- how does “Unleash” service and feature toggle come to this? Is this service to support described process or is it some other way of introducing new features?
- is it necessary to test all 4 feature levels in E2E tests on all clusters? That would results in quite a lot of jobs that would need to be monitored and examined constantly. Or maybe only production and beta?
- what is the process for prod-preview?
- how are che6, new launcher and new dashboard being introduced?
- how are we (QE) notified about new upcoming features and its rollout to production?

**Comment by ldimaggi** [comment]
This is a great topic for discussion!

I think that since the E2E tests are intended to function as regression tests, I would recommend that we focus on running E2E tests on production and prod-preview only.  We can certainly look at experimental, etc. features as they are developed, but it will be impossible for us to maintain a set of E2E tests as things change daily in development builds.

**Comment by ljelinkova** [comment]
Well, but our users accounts are set for  "internal features" - so, should we change that to production only? What features are in "internal features" that are not in "production"? Is there a list somewhere?

**Comment by ppitonak** [comment]
Although we have a continuous stream of changes to OSIO, my feeling is that only small fraction of them will break tests. I would still go with 4 accounts (set to internal, experimental, beta, production respectively) on a single cluster. If it proves to be a big maintenance burden, we would re-think the solution.

**Comment by ppitonak** [comment]
It would be handled similarly to how we handle various pipeline types.

**Comment by ljelinkova** [comment]
The code was changed to enable testing of different features so I am closing this issue now.
