### ISSUE TITLE
Design/implement tests to verify OSIO E2E operations within github organizations

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-test#587]
We have to expand our testing from scenarios where a user is working alone to also include githib organizations. Actions to verify include: if a user stops or deletes a pipeline, are the organizations remaining pipelines affected?

**Comment by ppitonak** [comment]
Although I believe that both single-user and team workflows are important, I think that only one of those should be tested by E2E tests, both of them should be tested by functional tests.

I personally would go for team workflow in E2E tests as soon as it's implemented and reasonably stable.

**Comment by ljelinkova** [comment]
Outdated.
