### ISSUE TITLE
Add test to check if stage and prod links are working

### ISSUE THREAD

**Issue by ljelinkova** [fabric8io/fabric8-test#588]
Add test that would open the stage and prod link and checked if the deployed application is working.

**Comment by ldimaggi** [comment]
We are starting to duplicate work work between the booster tests and the EE tests.

This booster test checks the deployed app at the Che preview URL. Can we create a shared/core functions to check for this URL and the stage and run links? Thx!

**Comment by ppitonak** [comment]
@rhopp is this part covered by your tests?

**Comment by rhopp** [comment]
Nope... Our tests currently do not operate outside of che. Thus we are not checking if pipeline finished successfully, nor we are checking whether deployment to stage/run namespaces was successfull.

**Comment by ppitonak** [comment]
@ldimaggi IMHO preview of stage/run environment and inside Che are two separate things.

**Comment by ppitonak** [comment]
@ldimaggi @ljelinkova isn't this a duplicate of #268?

**Comment by ljelinkova** [comment]
It seems so but if we are going to close one of them let it be #268.

**Comment by ljelinkova** [comment]
Done.
