### ISSUE TITLE
Report smoketest results into Zabbix

### ISSUE THREAD

**Issue by ljelinkova** [fabric8io/fabric8-test#609]
We would like to have 2 grahps in Zabbix:
- graph showing number of passed / failed / skipped tests
- graph showing duration of every test (it method) 

In order to do this, we would need
* [x] setup Zabbix
* [x] create custom Jasmine reporter
* [ ] sent data to Zabbix
* [ ] create graphs in Zabbix

From what I've learned from @Katka92, the format of data is `$ZABBIX_HOST $METRIC $ZABBIX_TIMESTAMP $VALLUE`, something like this (snippet from che functional tests)
```
qa_che.openshift.io createWorkspace-failed 1523845615 0
qa_che.openshift.io createWorkspace-fail_rate 1523845615 0
qa_che.openshift.io createWorkspace-rt_average 1523845615 1021
qa_che.openshift.io createWorkspace-rt_median 1523845615 840
qa_che.openshift.io createWorkspace-rt_min 1523845615 288
```

Our data would seem similar
```
qa.openshift.io login 1523845615 100
qa.openshift.io createSpace 1523845615 500
qa.openshift.io createQuickstart 1523845615 1021
qa.openshift.io runChe 1523845615 840
qa.openshift.io runPipeline 1523845615 2880
```

For skipped tests we would set value 0. 

Data are sent using 
```
zabbix_sender -vv -i $ZABBIX_LOG -T -z $ZABBIX_SERVER -p $ZABBIX_PORT;
```

**Comment by ljelinkova** [comment]
@pmacik could you help us with Zabbix setup?

**Comment by pmacik** [comment]
@ljelinkova Zabbix has been updated:
 * `qa_openshift.io` is a proper host name (the pattern is `qa_<osio-host>`)
 * I added a prefix to your metrics so it can be more easily found/filtered.

The sample zabbix file follows:
```
qa_openshift.io smoketest.login 1524236337 0
qa_openshift.io smoketest.createSpace 1524236337 0
qa_openshift.io smoketest.createQuickstart 1524236337 0
qa_openshift.io smoketest.runChe 1524236337 0
qa_openshift.io smoketest.runPipeline 1524236337 0
```

**Comment by ljelinkova** [comment]
I've asked SD team to create new group in Zabbix called QA - E2E. In that group we would have the following hosts:
- us-east-1a
- us-east-1b
- us-east-2
- us-east-2a

**Comment by ppitonak** [comment]
Test results are being correctly uploaded to Zabbix, charts were created.
