### ISSUE TITLE
E2E tests are failing intermittently failing due to OSIO env reset failing intermittently

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-test#635]
In our code to perform an env reset, we have to account for situations where the OSIO env reset fails to complete cleanly - for example:

![screenshot from 2018-04-27 08-34-45](https://user-images.githubusercontent.com/642621/39364858-5cc5eaf8-49fd-11e8-94d1-63c3173eee88.png)

**Comment by ldimaggi** [comment]
Related to - https://github.com/openshiftio/openshift.io/issues/1637

**Comment by ppitonak** [comment]
Do we want to try it again or something else?

**Comment by ldimaggi** [comment]
It looks as though the problem is that some spaces are not deleted - the Jenkins pod is restarted and that is what the tests care about.

**Comment by ldimaggi** [comment]
https://github.com/fabric8io/fabric8-test/pull/636

**Comment by ljelinkova** [comment]
Fixed by https://github.com/fabric8io/fabric8-test/pull/645
