### ISSUE TITLE
Fix e2e tests after beta features are released

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-test#652]
To do after beta features are released:

1. replace function `createSpace` in `ReleasedAccountHomeInteractions` with one of `BetaAccountHomeInteractions` 
2. remove function `createSpace` in `BetaAccountHomeInteractions` (leave empty class for future use)
3. replace function `createQuickstart` in `ReleasedSpaceDashboardInteractions` with one of `BetaSpaceDashboardInteractions`
4. replace function `verifyWorkItems` in `ReleasedSpaceDashboardInteractions` with one of `BetaSpaceDashboardInteractions`
5. remove functions `createQuickstart` and `verifyWorkItems` in `BetaSpaceDashboardInteractions` (leave empty class for future use)
6. (optionally) switch Jenkins jobs back to released - update all occurrences of `feature_level: beta` to `feature_level: released` in yaml (5 lines)
7. (if 6 merged) switch all OSIO accounts used by Jenkins job from beta features to released  

TODO:
1. replace content of function `createNewSpace` with `createNewSpaceByLauncher` in `MainDashboardPage` (will probably break booster tests)
2. replace content of function `newQuickstartProject` with `newQuickstartProjectByLauncher` in `AddToSpaceDialog` (will probably break booster tests)

**Comment by ljelinkova** [comment]
This was partially fixed by https://github.com/fabric8io/fabric8-test/pull/663

Lets keep track of the remaining tasks in https://github.com/fabric8io/fabric8-test/issues/677
