### ISSUE TITLE
Add some debug information in case pipeline fails

### ISSUE THREAD

**Issue by ljelinkova** [fabric8io/fabric8-test#670]
At the moment, when the pipeline fails, we do not have any additional information about the cause. We should at least take the screenshot of the Jenkins log and store the Jenkins log page source.

**Comment by ljelinkova** [comment]
Actually, it might be useful to check the Jenkins log in every test to see if it is accessible

**Comment by ldimaggi** [comment]
At one point, the E2E tests did access the Jenkins build log, and copy the text from that log into the tests' stdout. This action was removed from the tests as accessing the logs was blocked by this issue: https://github.com/openshiftio/openshift.io/issues/2752

But issue #2752 has not been seen for a while - so - I think we can once again have the tests access the Jenkins build logs.

**Comment by ljelinkova** [comment]
I think this is one good example why we should not comment out failing tests. 
1. I had no idea there was such issue
2. we do not know if it is still happening
3. we cannot confirm if it has been fixed

**Comment by ljelinkova** [comment]
Fixed by https://github.com/fabric8io/fabric8-test/pull/672
