### ISSUE TITLE
Review generated screenshots

### ISSUE THREAD

**Issue by ljelinkova** [fabric8io/fabric8-test#671]
We use reporter that creates screenshots and we also create our own screenshots. We should not duplicate them.

**Comment by ppitonak** [comment]
Can we remove the reported now?

**Comment by ljelinkova** [comment]
Yes, but only for the tests ran locally in docker.

We do have 2 options: 
1. Create directory in Javascript (the ScreenshotManager seems to be the right place)
2. Create directory in shell script ts-protractor.sh
