### ISSUE TITLE
Create automated regression tests for Jenkins/Content Repo Un-Idling

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-test#673]
Positive test paths to cover:
* [ ] User starts a new build, idle Jenkins/Content Repo are un-idled
* [ ] User promotes a build from stage to run, idle Jenkins/Content Repo are un-idled
* [ ] User accesses jenkins.openshift.io, idle Jenkins/Content Repo are un-idled
* [ ] Executes web-hook on github repo for OSIO app (crates a pull request), idle Jenkins/Content Repo are un-idled

Negative test paths to cover:
* [ ] User deletes build pipeline during promotion and un-idling, and creates new pipeline
* [ ] Does un-idling occur correctly when Jenkins or Content Repo quotas are exceeded?
* [ ] Can Jenkins un-idle correctly if Content Repo is started manually?
* [ ] Can Content Repo un-idle correctly if Jenkins is started manually?
* [ ] Can Jenkins un-idle correctly if Content Repo is stopped manually during un-idling?
* [ ] Can Content Repo un-idle correctly if Jenkins is stopped manually during un-idling?

**Comment by ldimaggi** [comment]
These tests should be constructed with the new idle/un-idle API/

**Comment by ljelinkova** [comment]
Outdated.
