### ISSUE TITLE
E2E and login tests are failing

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-test#720]
It looks as though the manner in which we are determining that dropdown menus and their items are 'ready' is failing. The tests have not changed - perhaps this is a change in angular?

**Comment by ppitonak** [comment]
Yes, looks like a change in Angular code, open home page in browser and watch `$('f8-app header > alm-app-header > nav .pull-right.dropdown')`

The menu is not there until you expand your menu.

**Comment by ppitonak** [comment]
Broken by one of these commits 
https://github.com/openshiftio/saas-openshiftio/commit/d4a0e91446bc85c89c2110dda45970ea242bec75
https://github.com/openshiftio/saas-openshiftio/commit/f4ace9b3cd3f7610fefddd296be9a2b81ca9fdd3

Job for e2e tests for prod-preview might reveal it sooner.

Working on fix
