### ISSUE TITLE
Create a test interacting with Che

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-test#736]
E2E tests should be expanded to also do something meaningful inside Che. Suggestions:

1. build project
2. start the app
3. change source code
4. verify that hot redeploy works
5. commit and push the change
6. verify that new build starts
7. verify that application works (#588)

We could call Java-based tests created by Che QE team instead of re-implemening it in our tests, see https://github.com/fabric8io/fabric8-test/issues/494#issuecomment-380021248

**Comment by ldimaggi** [comment]
This would be a good opportunity to share/re-use/integrate with the booster tests. 

See:

https://github.com/openshiftio/openshift.io/issues/2399

And:

https://github.com/fabric8io/fabric8-test/blob/master/ee_tests/protractor.config.ts#L86

**Comment by ljelinkova** [comment]
Done.
