### ISSUE TITLE
Refactor SpacePipelinePage

### ISSUE THREAD

**Issue by ljelinkova** [fabric8io/fabric8-test#742]
At the moment, there are 2 approaches used in this page

1. old approach - page contains methods for retrieving page obcets
```
/* Locate a pipeline by name */
  pipelineByName (nameString: string): ElementFinder {
    let xpathString = './/a[contains(@class,\'card-title\') and contains(text(),\'' + nameString + '\')]/../../..';
    return element(by.xpath(xpathString));
  }
```
2. new appriach - page contains methods for performing operations and retrieving page data
```
export class PipelineDetails extends BaseElement {

  constructor(finder: ElementFinder) {
    super(finder, 'Pipeline');
  }

  public async getApplicationName(): Promise<string> {
    return this.element(by.css('a.card-title[target="openshift"]')).getText();
  }
}
```

Since we should not have 2 different approaches and the new approach has proven as very successful in RedDeer project I suggest to start refactoring pages to use it. 

@ppitonak  @ldimaggi  @pmacik  WDYT?

**Comment by ppitonak** [comment]
+1 for new approach, it's well structured and easy to understand and extend for new people

**Comment by ldimaggi** [comment]
+1 yes - the new approach is much more maintainable.

**Comment by ljelinkova** [comment]
Done.
