### ISSUE TITLE
Add Planner to smoke test

### ISSUE THREAD

**Issue by ljelinkova** [fabric8io/fabric8-test#756]
Add some simple planner scenarion - like create work item, assign myself and check on the dashboard.

**Comment by ppitonak** [comment]
Remove `planner-simple-create.spec.ts` when done.

**Comment by rgarg1** [comment]
We can work together to identify the minimum tests required to validate Planner. You can borrow code from Planner existing test suite.

**Comment by Raunak1203** [comment]
@ljelinkova You can import https://www.npmjs.com/package/planner-functional-test package and we can use the page objects from this package. See https://github.com/fabric8io/fabric8-test/pull/731

**Comment by ppitonak** [comment]
@ljelinkova can we close it now?

**Comment by ljelinkova** [comment]
Yes.
