### ISSUE TITLE
Configure Protractor to stop on first failed expect

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-test#778]
This will run both `expect`s and report all the results. Sometimes it leads to `Cannot read property 'something' of undefined` errors because test is expected to stop on first failed expect.

```javascript
it('simple test', function () {
    // since this expect fails, this test should be marked failed and move to next it().
    let x: any[] = [];
    expect(x.length).toBe(4, 'first expect');
    // this expect should not be executed
    expect(x[3].something).toBe('second', 'second expect');
  });
```

```
1) test simple test
  - Expected 0 to be 4, 'first expect'.
  - Failed: Cannot read property 'something' of undefined
```

Supported by Jasmine 2.3 and newer, blocked by https://github.com/angular/protractor/issues/3234

**Comment by ljelinkova** [comment]
Current functionality where test fails after the it() method is good enough for now.
