### ISSUE TITLE
Provide prod-preview E2E/Smoketest results to production Pull Requests

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-test#803]
Josh suggested this: The idea is that each pull request to production would include a check of the most recent smoketest results on prod-preview. This would not be a perfect solution as there is a time delay, but, if the most recent smoketest run failed, pull requests on production would be blocked until the issue is resolved.

Josh:
_Can we add the results of the prod-preview e2e tests to any new PR in https://github.com/openshiftio/saas-openshiftio ? Something that goes and checks if it passing and posts that and blocks the PR._

**Comment by ppitonak** [comment]
Duplicate of #705
