### ISSUE TITLE
Evaluate additional tslint rules

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-test#837]
https://palantir.github.io/tslint/rules/no-any/
https://palantir.github.io/tslint/rules/only-arrow-functions/
https://palantir.github.io/tslint/rules/prefer-for-of/
https://palantir.github.io/tslint/rules/promise-function-async/
https://palantir.github.io/tslint/rules/typedef/
https://palantir.github.io/tslint/rules/await-promise/
https://palantir.github.io/tslint/rules/no-empty/
https://palantir.github.io/tslint/rules/no-floating-promises/
https://palantir.github.io/tslint/rules/no-implicit-dependencies/
https://palantir.github.io/tslint/rules/no-inferred-empty-object-type/
https://palantir.github.io/tslint/rules/no-return-await/
https://palantir.github.io/tslint/rules/no-null-keyword/
https://palantir.github.io/tslint/rules/prefer-conditional-expression/
https://palantir.github.io/tslint/rules/deprecation/
https://palantir.github.io/tslint/rules/prefer-const/

**Comment by ljelinkova** [comment]
Outdated.
