### ISSUE TITLE
Colorize log output

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-test#874]
package for writing colorful text to console: https://www.npmjs.com/package/chalk

ideas:
- different color for info and debug logging

**Comment by ljelinkova** [comment]
Partially fixed by https://github.com/fabric8io/fabric8-test/commit/f2211dfde428ee403ab7ed3dfeae55caa636ae4b

Remaining issue tracked here: https://github.com/fabric8io/fabric8-test/issues/948
