### ISSUE TITLE
Console log is not colorful when running inside docker

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-test#948]

**Comment by ljelinkova** [comment]
I tried different library (used by Jasmine reporter) but it did not work either. 

I checked the output of npm run image:start > /tmp/output.txt and there were no generated meta tags

However, when I typed the color directly, the output in Docker was in color and meta tags present. 
console.log('\x1b[32m----------%s----------\x1b[0m', msg);

**Comment by ppitonak** [comment]
Adding `-e "FORCE_COLOR=1"` to `docker run` command in `*cico_run_e2e_tests.sh` helps a bit... the only thing that doesn't work is `script` which is supposed to be dimmed. 

1. I suggest to change `dim` to `gray`
2. I suggest to change `specTitle` from `greenBright` to `green` which is more readable on light background

this is how it would look like (specTitle contains green on the left, greenBright on the right)
![e2e_log_breeze](https://user-images.githubusercontent.com/445100/44530107-fbfe3100-a6ed-11e8-906b-ed763ade42d8.png)
![e2e_log_linux](https://user-images.githubusercontent.com/445100/44530108-fc96c780-a6ed-11e8-815f-0fb0a0823145.png)
![e2e_log_white](https://user-images.githubusercontent.com/445100/44530109-fc96c780-a6ed-11e8-8b79-bb346b9d2733.png)

**Comment by ljelinkova** [comment]
Thanks for great investigation :-)

I changed greenBright to green. I left dim as it was because it seems to work correctly although it is a bit more difficult to read.

**Comment by ljelinkova** [comment]
Fixed by #1009
